apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "apt-exporter.fullname" . }}
  labels:
    {{- include "apt-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "apt-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apt-exporter.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "apt-exporter.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: apt-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 9120
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - SYS_CHROOT
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: host-root
          hostPath:
            path: /
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
