apiVersion: v1
kind: Service
metadata:
  name: {{ include "apt-exporter.fullname" . }}
  labels:
    {{- include "apt-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9120"
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "apt-exporter.selectorLabels" . | nindent 4 }}
